import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import ReduxProvider from '@/redux/ReduxProvider'
import { ToastNotification } from '@/components/toast'
import './globals.css'

const urbanist = Urbanist({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Tejash Creation - Admin',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={urbanist.className}>
        <ReduxProvider>
          <ToastNotification />
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
